In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [3]:
zeroArray = np.zeros((2,3))

In [4]:
zeroArray

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
print zeroArray

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [6]:
oneArray = np.ones((2,3))

In [7]:
oneArray

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
randomArray = np.random.random((2,3))

In [9]:
randomArray

array([[ 0.77326573,  0.02943911,  0.5380771 ],
       [ 0.90732531,  0.25313672,  0.53587094]])

In [10]:
randomArray[1,1]

0.25313671637986424

In [11]:
randomArray[0,0]

0.77326572528117465

In [12]:
foo = [[1,2,3], [4, 5, 6]]

In [13]:
foo

[[1, 2, 3], [4, 5, 6]]

In [14]:
rangeArray = np.arange(6,12)

In [15]:
rangeArray

array([ 6,  7,  8,  9, 10, 11])

In [16]:
rangeArray.reshape((2,3))

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
rangeArray

array([ 6,  7,  8,  9, 10, 11])

In [18]:
rangeArray = rangeArray.reshape((2,3))

In [19]:
rangeArray

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
rangeArray.reshape((3,2))

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
squareArray = np.arange(1,10).reshape((3,3))

In [22]:
squareArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
squareArray[0,0:2]

array([1, 2])

In [24]:
squareArray[0,1:2]

array([2])

In [25]:
squareArray[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [26]:
squareArray[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [27]:
randomRow = np.random.random((10,1))

In [28]:
randomRow

array([[ 0.41384224],
       [ 0.49127025],
       [ 0.61904387],
       [ 0.63480148],
       [ 0.96539223],
       [ 0.14456939],
       [ 0.1239282 ],
       [ 0.77362264],
       [ 0.93904696],
       [ 0.00280433]])

In [29]:
fibIndices = np.array([1,1,2,3])

In [30]:
randomRow[fibIndices]

array([[ 0.49127025],
       [ 0.49127025],
       [ 0.61904387],
       [ 0.63480148]])

In [31]:
boolIndices = np.array([[True, False, True], [False, True, False], [True, False, True]])

In [32]:
print squareArray[boolIndices]

[1 3 5 7 9]


In [33]:
np.average(squareArray)

5.0

In [34]:
np.median(squareArray)

5.0

In [35]:
np.sum(squareArray)

45

In [36]:
np.sum(squareArray[:,0])

12

In [37]:
sqAverage = np.average(squareArray)

In [38]:
betterThanAverage = squareArray > sqAverage

In [40]:
betterThanAverage

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [41]:
freq = squareArray

In [42]:
freq[1,1] = 0

In [43]:
freq

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [44]:
squareArray

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [46]:
freq[1,1] = 5

In [47]:
freq[1,1] = 0

In [48]:
squareArray

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [49]:
freq

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [50]:
freq[1,1] = 5

In [51]:
freq

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
squareArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
freq = squareArray.copy()

In [54]:
freq[1,1] = 0

In [55]:
squareArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
clampedSqArray = np.array(squareArray.copy(), dtype=float)

In [59]:
sqStdDev = squareArray.std()

In [60]:
sqStdDev

2.5819888974716112

In [61]:
clampedSqArray[(squareArray-sqAverage) > sqStdDev] = sqAverage+sqStdDev

In [62]:
clampedSqArray

array([[ 1.       ,  2.       ,  3.       ],
       [ 4.       ,  5.       ,  6.       ],
       [ 7.       ,  7.5819889,  7.5819889]])

In [63]:
print squareArray+1

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [64]:
print squareArray * np.arange(1,10).reshape((3,3))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [65]:
matA = np.array([[1,2], [3,4]])

In [66]:
matB = np.array([[5,6], [7,8]])

In [67]:
np.dot(matA, matB)

array([[19, 22],
       [43, 50]])

In [68]:
import QSTK.qstkutil.qsdateutil as du
import QSTK.qstkutil.tsutil as tsu
import QSTK.qstkutil.DataAccess as da

import datetime as dt
import matplotlib.pyplot as plt
import pandas as pd

ImportError: No module named QSTK.qstkutil.qsdateutil